abstract class ProfileScreenState {}
class InitialState extends ProfileScreenState{}
class UpdateProfileScreenSuccessState extends ProfileScreenState{}
class UpdateProfileScreenLoadingState extends ProfileScreenState{}
class UpdateProfileScreenErrorState extends ProfileScreenState{}
class FetchCitySuccessState extends ProfileScreenState{}
class FetchCityLoadingState extends ProfileScreenState{}
class FetchCityErrorState extends ProfileScreenState{}
class ChangePickedDateState extends ProfileScreenState{}
class ChangeAddressState extends ProfileScreenState{}
class UpdatePasswordSuccessState extends ProfileScreenState{}
class UpdatePasswordErrorState extends ProfileScreenState{}
class UpdatePasswordLoadingState extends ProfileScreenState{}
